config/routes.rb
Rails.application.routes.draw do
  resources :foods, only: [:index, :new, :create, :show, :destroy]
  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :ingredients, only: [:new,  :create, :edit, :update, :destroy]
    
    member do
      patch 'toggle_public'
      get 'new_food'
    end
  end
  
  devise_for :users
  get '/public_recipes', to: 'recipes#public_list'
  get 'general_shopping_list', to: 'shopping_list#index', as: 'general_shopping_list'
  root to: "users#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user.present?

    can :read, :public_recipes
    can :read, Recipe, public: true

    can :manage, Recipe, user_id: user.id
    can :manage, Food, user_id: user.id
    can :manage, RecipeFood, recipe: { user_id: user.id }
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods

  validates :food, presence: true
  validates :measurement_unit, presence: true
  validates :unit_price, numericality: true # Use `numericality: true` to validate numericality
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :food
  belongs_to :recipe

  validates :quantity, presence: true
  validates :value, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :ingredients

  validates :name, presence: true
  validates :description, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :public_recipe, inclusion: { in: [true, false] }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food, class_name: 'Food', foreign_key: :food_id
  belongs_to :recipe, class_name: 'Recipe', foreign_key: :recipe_id

  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :food_id, presence: true
  validates :recipe_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :current_user
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def index
    @foods = current_user.foods
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.new(food_params)
    if @food.save
      redirect_to foods_path, notice: 'Food added successfully.'
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path, notice: 'Food item deleted successfully.'
  end

  private

  def food_params
    params.require(:food).permit(:food, :unit_price, :measurement_unit, :quantity)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id]) # Assuming you have a route like /recipes/:recipe_id/ingredients/new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to @ingredient.recipe, notice: 'Ingredient was successfully added.'
    else
      render :new
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
    @recipe = Recipe.find(params[:recipe_id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update(ingredient_params)
      redirect_to recipe_path(params[:recipe_id]), notice: 'Ingredient updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.find(params[:id])
    @ingredient.destroy
    redirect_to recipe_path(params[:recipe_id]), notice: 'Ingredient updated successfully.'
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:food_id, :recipe_id, :quantity, :value)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.where(user_id: current_user.id)
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.build(recipe_food_params)

    if @recipe_food.save
      redirect_to recipe_path(@recipe.id), notice: 'Food added from the recipe successfully.'
    else
      @foods = Food.all
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.destroy
      redirect_to recipe_path(@recipe.id), notice: 'Food removed form the recipe successfully.'
    else
      flash.now[:alert] = 'Failed to remove food from recipe foods list.'
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: %i[destroy toggle_public new_food]

  def index
    @recipes = current_user.recipes
  end

  def new
    @recipe = Recipe.new
  end

  def toggle_public
    @recipe = current_user.recipes.find(params[:id])
    @recipe.toggle!(:public_recipe)
    redirect_to recipe_path(@recipe)
  end

  def new_food
    @food = Food.new
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def destroy
    @recipe = current_user.recipes.find(params[:id])
    @recipe.ingredients.destroy_all
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe deleted successfully.'
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe created successfully.'
    else
      puts @recipe.errors.full_messages # Add this line for debugging
      render :new
    end
  end

  def public_list
    @public_recipes = Recipe.where(public_recipe: true).order(created_at: :desc)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    foods = Food.includes(:recipe_foods).where({ user_id: current_user.id })
    @shopping_list = []
    @total_price = 0
    foods.each do |food|
      shopping_list_item = {
        food: food.food,
        quantity: calculate_missing_food(food),
        unit: food.measurement_unit,
        unit_price: food.unit_price
      }
      @total_price += shopping_list_item[:quantity] * shopping_list_item[:unit_price]
      @shopping_list << shopping_list_item if (shopping_list_item[:quantity]).positive?
    end
  end

  private

  def calculate_missing_food(food)
    food.quantity.to_i
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index; end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/views/foods/create.html.erb
<h1>Foods#create</h1>
<p>Find me in app/views/foods/create.html.erb</p>

app/views/foods/index.html.erb
<%= stylesheet_link_tag 'food', media: 'all', 'data-turbolinks-track': 'reload' %>

<p style="color: green"><%= notice %></p>

<div class="table-info">

<div class="new-food-container">
  <%= link_to "ADD FOOD", new_food_path, class: "new-food" %>
</div>

<table border="2">
  <tr>
    <th>Food</th>
    <th>Measurement Unit</th>
    <th>Unit Price</th>
    <th>Quantity</th>
    <th>Actions</th>
  </tr>
<% @foods.each do |food| %>
    <tr>
      <td><%= food.food %></td>
      <td><%= food.measurement_unit %></td>
      <td>$<%= food.unit_price %></td>
      <td><%= food.quantity %></td>
      <td>
        <%# <%= link_to "Show", food %> 
        <%# <%= link_to "Edit", edit_food_path(food) %> 
        <%= link_to "Delete", food, method: :delete, data: { confirm: "Are you sure?" }, class: "delete-food" %>
      </td>
    </tr>
  <% end %>
</table>
<div>

app/views/foods/new.html.erb
<%= stylesheet_link_tag 'addFood', media: 'all', 'data-turbolinks-track': 'reload' %>

<h1>Add New Food</h1>

<div class="form-container">
  <%= form_with model: @food, url: foods_path do |form| %>
    <div>
      <%= form.label :food %>
      <%= form.text_field :food %>
    </div>

    <div>
      <%= form.label :unit_price %>
      <%= form.number_field :unit_price %>
    </div>

     <div>
      <%= form.label :quantity %>
      <%= form.number_field :quantity %>
    </div>

    <div>
      <%= form.label :measurement_unit %>
      <%= form.text_field :measurement_unit %>
    </div>

    <div>
      <%= form.submit "Add Food" %>
    </div>
  <% end %>
</div>

app/views/foods/show.html.erb
<h1><%= @food.food %></h1>
<p>Unit Price: <%= @food.unit_price %></p>
<p>Unit Price: <%= @food.quantity %></p>
<p>Measurement Unit: <%= @food.measurement_unit %></p>

<%= button_to "Destroy this food", @food, method: :delete %>

app/views/ingredients/create.html.erb
<h1>Ingredients#create</h1>
<p>Find me in app/views/ingredients/create.html.erb</p>

app/views/ingredients/destroy.html.erb
<h1>Ingredients#destroy</h1>
<p>Find me in app/views/ingredients/destroy.html.erb</p>

app/views/ingredients/edit.html.erb
<%= form_with(model: @ingredient, url: recipe_ingredient_path(@recipe, @ingredient), method: :patch) do |form| %>
  <div>
    <%= form.label :food_id, "Food" %>
    <%= form.collection_select :food_id, Food.all, :id, :food, { selected: @ingredient.food.id } %>
  </div>

  <div>
    <%= form.label :quantity %>
    <%= form.number_field :quantity, value: @ingredient.quantity %>
  </div>

  <div>
    <%= form.label :value %>
    <%= form.text_field :value, value: @ingredient.value %>
  </div>

  <%= form.hidden_field :recipe_id, value: @recipe.id %>

  <div>
    <%= form.submit "Update Ingredient" %>
  </div>
<% end %>

app/views/ingredients/new.html.erb
<%= form_with(model: @ingredient, url: recipe_ingredients_path(@recipe)) do |form| %>
  <div>
    <%= form.label :food_id, "Food" %>
    <%= form.collection_select :food_id, Food.all, :id, :food %>
  </div>

  <div>
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :value %>
    <%= form.number_field :value %>
  </div>

  <%= form.hidden_field :recipe_id, value: @recipe.id %>

  <div>
    <%= form.submit "Add Ingredient" %>
  </div>
<% end %>

app/views/ingredients/update.html.erb
<h1>Ingredients#update</h1>
<p>Find me in app/views/ingredients/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeAppCapstone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload"%>
  </head>

  <body>
  <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<%= stylesheet_link_tag 'recipes_list', media: 'all', 'data-turbolinks-track': 'reload' %>

<h1>Recipes List</h1>

<% @recipes.each do |recipe| %>
  <div  class="recipes-list">
    <h2 class="header"><%= link_to recipe.name, recipe %></h2>
    <p class="description"><%= recipe.description %></p>
    <% if recipe.user == current_user %>
      <%= link_to "Remove", recipe, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-button" %>
    <% end %>
  </div>
<% end %>

app/views/recipes/new.html.erb
<%= stylesheet_link_tag 'recipes', media: 'all', 'data-turbolinks-track': 'reload' %>

<h1>Add New Recipe</h1>

<div class="new-recipe-container">
  <%= form_with model: @recipe, url: recipes_path do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div>
      <%= form.label :preparation_time %>
      <%= form.number_field :preparation_time %>
    </div>

    <div>
      <%= form.label :cooking_time %>
      <%= form.number_field :cooking_time %>
    </div>

    <div>
      <%= form.submit "Add Recipe" %>
    </div>
  <% end %>
</div>

app/views/recipes/public_list.html.erb
<!-- app/views/recipes/public_list.html.erb -->
<h1>Public Recipe List</h1>
<ul>
  <% @public_recipes.each do |recipe| %>
    <li><%= link_to recipe.name, recipe %></li>
  <% end %>
</ul>

app/views/recipes/show.html.erb
<%= stylesheet_link_tag 'public', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="recipe-details">
  <h1><%= @recipe.name %></h1>
  <p><%= @recipe.description %></p>
  <p class="time-info">Preparation Time: <%= @recipe.preparation_time %> hours</p>
  <p class="time-info">Cooking Time: <%= @recipe.cooking_time %> hours</p>

  <% if @recipe.user == current_user %>
    <%= form_with model: @recipe, url: toggle_public_recipe_path(@recipe), method: :patch do |form| %>
      <%= form.submit @recipe.public_recipe ? "Make Private" : "Make Public", class: "toggle-button" %>
    <% end %>
    <%= button_to "Destroy this recipe", @recipe, method: :delete, class: "delete-button" %>

<%= link_to "Add Ingredient", new_recipe_ingredient_path(@recipe), class: "add-button" %>
          <%= link_to 'generate shopping list', general_shopping_list_path , class: "add-shoppinng-button"%>
    

  <% else %>
    <% if @recipe.user == current_user || @recipe.public_recipe %>
      <!-- Display recipe details -->
    <% else %>
      <p>This recipe is private.</p>
    <% end %>
  <% end %>
</div>

<h2 class="headers">Ingredients</h2>
<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe.ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.food.food %></td>
        <td><%= ingredient.quantity %></td>
        <td><%= ingredient.value %></td>
        <td>
        <div class="buttons">
          <%= link_to "Edit", edit_recipe_ingredient_path(@recipe, ingredient) %>
          <%= button_to 'Delete', recipe_ingredient_path(@recipe, ingredient), method: :delete, data: { confirm: 'Are you sure?' } %>
        <div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-success "> 
   <div class="container-fluid text-white"> 
     <a class="navbar-brand">Recipes</a> 
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"> 
       <span class="navbar-toggler-icon"></span> 
     </button> 
    <div class="collapse navbar-collapse" id="navbar"> 
       <ul class="navbar-nav"> 
         <% if user_signed_in? %> 

         <li class="nav-item"> 
             <%= link_to "Add Food", new_food_path ,class: "nav-link" %>
           </li> 
                     
           <li class="nav-item"> 
             <%= link_to "Food List", foods_path, class: "nav-link" %>
           </li> 

            <li class="nav-item">
           <%= link_to "Add Recipe", new_recipe_path, class: "nav-link" %>
           </li>
  
           <li class="nav-item">
           <%= link_to "Recipes List", recipes_path, class: "nav-link" %>
           </li>
  
           <li class="nav-item"> 
             <li><%= link_to "Public Recipes", public_recipes_path, class: "nav-link" %></li>
           </li> 
  
           <li class="nav-item"> 
             <%= button_to "Sign Out", destroy_user_session_path, method: :delete, form_class: "nav-link" %> 
           </li> 
  
         <% else %> 
           
         <% end %> 
       </ul> 
     </div> 
 </nav>

app/views/shopping_list/index.html.erb
<div class="row justify-content-center mt-4">
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <div class="container d-flex justify-content-center">
                    <h1>Shopping list</h1>
                </div>
                    <div class="container d-flex justify-content-between">
                        <p>Amount of food to buy: <span><%= @shopping_list.length %></span></p>
                        <p>Total value of food needed: <%= @total_price %></span> $</p>
                    </div>
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Food</th>
                                <th>Quantity</th>
                                <th>Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @shopping_list.each do |shopping_list_item| %>
                                <tr>
                                    <td><%= shopping_list_item[:food] %></td>
                                    <td><%= "#{shopping_list_item[:quantity]} #{shopping_list_item[:unit]}" %></td>
                                    <td><%= "#{shopping_list_item[:unit_price] * shopping_list_item[:quantity]} $" %></td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>>
</div>

app/views/users/index.html.erb
<%# <%= stylesheet_link_tag 'navbar', media: 'all', 'data-turbolinks-track': 'reload' %>

<h1>Welcome to Our Page</h1>